### ISSUE TITLE
Global CSS cannot be imported from within node_modules

### ISSUE THREAD

**Issue by rmanalan** [creativetimofficial/material-tailwind#30]
In trying to use the `Popover` component in a Nextjs codebase,

```
import Popover from '@material-tailwind/react/Popover'
...
<Popover placement='left' ref={targetRef}>
  <PopoverContainer>
    <PopoverHeader>{prop.title}</PopoverHeader>
    <PopoverBody>{prop.description}</PopoverBody>
  </PopoverContainer>
</Popover>
```

I get the following error in Nextjs:

```
wait  - compiling...
error - ./node_modules/tippy.js/dist/svg-arrow.css
Global CSS cannot be imported from within node_modules.
Read more: https://nextjs.org/docs/messages/css-npm
Location: node_modules/@material-tailwind/react/Popover.js
```

Nextjs doesn't like it when a package is importing a CSS file from another module. See: https://nextjs.org/docs/messages/css-npm

**Comment by sajadevo** [comment]
@rmanalan Thanks for your helpful feedback for making material tailwind better,

We will fix this issue in the new version of material tailwind.

**All the best**
**Sajad**

**Comment by sajadevo** [comment]
@rmanalan The issue that you have mentioned is now fixed in the material tailwind v0.3.0 and you can use it now normally.

**Comment by rmanalan** [comment]
Wow... that was fast. Thanks!


On April 26, 2021 at 7:44 AM, Sajad Ahmad Nawabi ***@***.***) wrote:
@rmanalan ( https://github.com/rmanalan ) The issue that you have mentioned is now fixed in the material tailwind v0.3.0 and you can use it now normally.

**Comment by sajadevo** [comment]
@rmanalan Thanks a lot we appreciate our user feedback if you found other issues with material tailwind feel free and add it here we will fix it as soon as possible. 🙏

**Comment by rmanalan** [comment]
Still getting the issue with 0.3.0:

![image](https://user-images.githubusercontent.com/549/116321998-03641b00-a770-11eb-9db8-1775ca17259c.png)

**Comment by EINazare** [comment]
Hey @rmanalan ,

Could you share your project with us? Or a minimal project with the issue?
Alternatively, you can share with us some steps to reproduce your issue, for example:
1. Run in terminal `npx create-next-app text-material-tailwind`
2. Install material tailwind: `npm i -E @material-tailwind/react`
3. Add the following code inside `App.js`
4. etc.
Something like that?

Thank you,
Manu

**Comment by sajadevo** [comment]
Hey @rmanalan,

Thanks again for helping us to make the material tailwind better 🙏

The issue that you have mentioned is with the style sheets of tippy.js and not working for popover, tooltips and dropdown components but now we compiled it into the tailwind.css file our main style sheet for material tailwind that hold everything about the style.
I have update the library and now its working fine 😊

Just follow these steps:

1. Import the tailwind.css file from the material-tailwind in to your _app.js file.
i.e: `import "@material-tailwind/react/tailwind.css";`

2. Import the popover components you want to use: Popover, PopoverContainer, PopoverHeader, PopoverBody.
3. Create a ref using useRef() and add it for the Popover component on ref prop and as well as add the ref to the element you want to trigger popover with.
i.e: `
import { useRef } from 'react';
import Popover from '@material-tailwind/react/Popover';
import PopoverContainer from '@material-tailwind/react/PopoverContainer';
import PopoverHeader from '@material-tailwind/react/PopoverHeader';
import PopoverBody from '@material-tailwind/react/PopoverBody';
import Button from '@material-tailwind/react/Button';

export default function Example() {
    const targetRef = useRef();

    return (
        <>
            <Button color="purple" ripple="light" ref={targetRef}>
                Open Popover
            </Button>

            <Popover placement="bottom" ref={targetRef}>
                <PopoverContainer>
                    <PopoverHeader>Popover Title</PopoverHeader>
                    <PopoverBody>Popover content...</PopoverBody>
                </PopoverContainer>
            </Popover>
        </>
    );
}
`

If you face with other issues when using material tailwind feel free to tell us about it.

**All the best**
**Sajad**

**Comment by sajadevo** [comment]
```
import { useRef } from "react";
import Popover from "@material-tailwind/react/Popover";
import PopoverContainer from "@material-tailwind/react/PopoverContainer";
import PopoverHeader from "@material-tailwind/react/PopoverHeader";
import PopoverBody from "@material-tailwind/react/PopoverBody";
import Button from "@material-tailwind/react/Button";

export default function Example() {
    const targetRef = useRef();

    return (
        <>
            <Button color="purple" ripple="light" ref={targetRef}>
                Open Popover
            </Button>

            <Popover placement="bottom" ref={targetRef}>
                <PopoverContainer>
                    <PopoverHeader>Popover Title</PopoverHeader>
                    <PopoverBody>Popover content...</PopoverBody>
                </PopoverContainer>
            </Popover>
        </>
    );
}
```
